apiVersion: v1

kind: Service

metadata:

  name: product-service

spec:

  selector:

    app: product-service

  ports:

    - name: http

      port: 3002

      targetPort: 3002

  type: ClusterIP